### ISSUE TITLE
Darstellung von Timestamps

### ISSUE THREAD

**Issue by baehll** [baehll/neosyn#101]
Hallo @cknott 

mir ist aufgefallen, dass Timestamps falsch in der UI dargestellt werden, bspw wird aus "Thu, 16 May 2024 13:03:24 GMT" -> "2024-05-16 01:42"

die Zeitzone muss ich serverseitig noch hinzufügen

**Comment by baehll** [comment]
beim genaueren hinsehen stimmt die Zeit, sollte wahrscheinlich aber im 24h stunden Format dargestellt werden

**Comment by cknott** [comment]
ist angepasst
