### ISSUE TITLE
CSP für Social Media Post Media

### ISSUE THREAD

**Issue by cknott** [baehll/neosyn#102]
hi @baehll wir müssen die csp erweitern/öffnen, da gerade die bilder von den meta/instagram nicht geladen werden können.
bin mir nicht sicher ob wir es schaffen immer alle server explizit angeben zu können oder ob wir die csp komplett öffnen müssen.

**Comment by baehll** [comment]
Ich habe mal den CDN von instagram aus der URL hinzugefügt, wenn das nicht hält werde ich das ganz offen machen müssen
