### ISSUE TITLE
user avatar in einem thread

### ISSUE THREAD

**Issue by cknott** [baehll/neosyn#103]
hi @baehll ich benötige den user avatar für die nachrichten darstellung in einem thread an den messages. da ich diese info nur pro thread benötige, wäre es super wenn ich die url für diesen avatar direkt in der thread liste als weitere json property erhalten könnte.

**Comment by baehll** [comment]
Das Problem bei Instagram ist, dass man Profilbilder von anderen Business Usern über die API anfragen kann, weshalb diese dann leer bzw. als None in den responses aufgeführt werden für "normale" Nutzer.
Das Feld in der response dafür heißt "avatar"

**Comment by cknott** [comment]
@baehll ok, das heisst bei einer interaktion durch einen normalen nutzer kriegen wir das avatar nicht?

**Comment by baehll** [comment]
ja, das gibt es nur bei anderen business accounts
