### ISSUE TITLE
bookmark setzen endpoint - PUT ist nicht erlaubt

### ISSUE THREAD

**Issue by cknott** [baehll/neosyn#105]
hi @baehll beim put request auf den bookmark setzen endpoint (/api/data/threads/bookmark/4) erhalte ich http 405 method not allowed

**Comment by baehll** [comment]
hast du sichergestellt, dass es auf /api/data/threads/bookmark**s**/<id> geht?

**Comment by cknott** [comment]
ah, sorry, ist in dev gefixt!
