### ISSUE TITLE
CORS / CSP Problem bei early_access API Aufruf

### ISSUE THREAD

**Issue by cknott** [baehll/neosyn#11]
Hi @baehll 

wenn ich auf der Coming Soon Seite den Early Access Login probiere, wird das Request blockiert. Die URL lautet https://quiet-mountain-69143-51eb8184b186.herokuapp.com/auth/early_access

Kannst du die API auf derselben Domain betreiben bzw. unter einer Subdomain?

Viele Grüße
Christian

**Comment by baehll** [comment]
CSP wurde jetzt richtig konfiguriert, Anfragen klappen und in der Konsole sind keine Fehlermeldungen
