### ISSUE TITLE
antworten landen nicht im nachrichtenverlauf

### ISSUE THREAD

**Issue by cknott** [baehll/neosyn#117]
hi @baehll 
ich habe gestern ein paar kommentare geschrieben und heute auf einen kommentar über das unaite.ai backend geantwortet (bei dem graf zahl post). der kommentar erscheint auf instagram korrekt als antwort zu meinem kommentar, im backend wird diese antwort allerdings als komplett neuer thread angezeigt und nicht als nachricht innerhalb meines threads.

**Comment by baehll** [comment]
ja, das ist mir auch aufgefallen, an der stelle arbeite ich noch gerade

versuche auch dabei, das ganze ein bisschen flotter zu machen

**Comment by baehll** [comment]
sollte nun gefixt sein
