### ISSUE TITLE
post media urls expiren

### ISSUE THREAD

**Issue by cknott** [baehll/neosyn#122]
hi @baehll mir ist gerade aufgefallen dass die medien von posts nicht mehr geladen werden können (status code 403 von instagram) weil es wohl eine signatur in der url gibt, welche nach etwas zeit expired. bin mir nicht sicher was hier der richtige ansatz wäre, möglicherweise müsste der post heruntergeladen und nicht gehotlinked werden.

**Comment by baehll** [comment]
hey @cknott könntest du mir sagen, in welcher response die url ist? post inhalte zu speichern sollte nicht so schlimm sein, solange nicht die medien auch gespeichert werden müssen

**Comment by cknott** [comment]
Sorry, ich meine die medien. Ist in der response des endpoints der die infos zu einem post liefert, also inhalt, likes, shares erc Am 27.05.2024 um 22:15 schrieb baehll ***@***.***>:﻿
hey @cknott könntest du mir sagen, in welcher response die url ist? post inhalte zu speichern sollte nicht so schlimm sein, solange nicht die medien auch gespeichert werden müssen

**Comment by baehll** [comment]
ich denke, dass das im eigentlichen betrieb kein problem sein wird, da die URLs beim updaten der Daten überschrieben werden mit neuen media_urls. 
wenn über lange zeit nichts geupdatet wurde, dann könnten sie ablaufen, jedoch ist geplant, regelmäßige updates zu machen, um die Sentiments und Analysen zu den Social Media Interaktionen aktuell zu halten

**Comment by baehll** [comment]
wird mit dem nächsten dev update gefixt sein
