### ISSUE TITLE
POST /api/data/threads - Filterung / Sortierung

### ISSUE THREAD

**Issue by cknott** [baehll/neosyn#123]
Hi @baehll 
wir haben gerade einen GET und einen POST Endpunkt für eigentlich dieselbe Anfrage mit ein paar optionalen Parametern.
Aus meiner Sicht reicht es wenn wir die POST Variante behalten, da ich ja die GET Parameter trotzdem an die URL hängen kann, würde folgende Struktur vorschlagen: /api/data/threads?sorting=xyz&offset=123 mit post body q, platforms und sentiments.
alle parameter und post body inhalte sind optional. was meinst du?

**Comment by baehll** [comment]
klingt sinnvoll, werde das ändern und einmal testen

**Comment by baehll** [comment]
hi @cknott 
In der Anfrage wird aktuell der payload `{ "q" : null }` gesendet, auch wenn kein Inhalt in der Suche ist.
kannst du das so machen, dass bei leeren Suchstring auch das Feld nicht geschickt wird?

**Comment by cknott** [comment]
@baehll ist jetzt in dev!

**Comment by baehll** [comment]
scheint alles richtig zu sein
ich erweitere den Endpunkt, damit man auch nach den ungelesenen/gelesenen Threads filtern kann, das haben wir noch nicht bedacht

**Comment by baehll** [comment]
hey @cknott 
ist auf dev, wenn du das hast, kannst du auch in main mergen

**Comment by cknott** [comment]
hi @baehll sieht gut aus!
