### ISSUE TITLE
endpunkt zum löschen eines threads

### ISSUE THREAD

**Issue by cknott** [baehll/neosyn#125]
hi @baehll ich brauche noch einen endpunkt der einen thread löscht, bin mir allerdings nicht sicher was hier backendseitig passieren soll, also ob der eigentlich kommentar auf instagram dann ebenfalls gelöscht werden soll oder ob nur dieser thread aus dem backend gelöscht / versteckt werden soll.

**Comment by baehll** [comment]
Die Idee war, auch den Kommentar zu löschen auf der Plattform, deshalb sollte davor noch eine Sicherheitsabfrage gemacht werden.
Den Endpunkt habe ich bereits im backend branch, wenn ich noch einen Bug hier gefixt habe bring ich das auf dev

**Comment by baehll** [comment]
ist in dev
