### ISSUE TITLE
File Upload / init_user Endpunkt

### ISSUE THREAD

**Issue by cknott** [baehll/neosyn#13]
Hi @baehll 

mir ist gerade aufgefallen, dass in dem init_user Endpunkt sowohl auf einen JSON Request Body als auch direkt auf die angehängten Files zugegriffen wird, aus meiner Sicht ist das so nicht möglich.
Ich sehe gerade zwei Wege hierfür:
1) ich sende die Daten als ein Standard POST Request als multipart/form-data und die Daten für username, company kommen als Standard Formular Felder und die Uploads kommen im Files Array

2) wir teilen die Erstellung des Accounts in zwei Requests auf wobei beim ersten username / company gesetzt werden und beim zweiten bzw. dritten das Logo und die anderen Dateien gesendet werden.

Was meinst du?

Viele Grüße
Christian

**Comment by baehll** [comment]
Hallo @cknott 

dann würde ich die erste Lösung vorschlagen, das erscheint mir am besten.

-Fabian

**Comment by baehll** [comment]
Ist nun im dev Branch umgesetzt
