### ISSUE TITLE
POST thread message 

### ISSUE THREAD

**Issue by baehll** [baehll/neosyn#132]
hallo @cknott 

beim POST request zum Posten eines generierten Kommentars (/api/data/threads/<id>/message) sollte das Feld "generated_message" nur vorhanden sein, wenn die generierte Antwort abgeändert wurde, ansonsten kann das Feld wegbleiben

**Comment by cknott** [comment]
hi @baehll ist im aktuellen stand behoben, habe gerade in dev + main gemerged
