### ISSUE TITLE
URL Struktur 

### ISSUE THREAD

**Issue by cknott** [baehll/neosyn#16]
Hi @baehll & @xam4 

wie angekündigt hier meine Gedanken zur Struktur der Seite:

*Meta / Content Seiten*
Alle Info Seiten wie auch die jetzige Coming Soon Seite würde ich unter der Toplevel Domain neosyn.ai (oder auch der zukünftigen) ausliefern.

*Login / Registrierung / App*
Sobald auf eine der eigentlichen interaktiven Bereiche zugegriffen wird, würde ich auf die Subdomain app.neosyn.ai wechseln und dort folgende - von Python gerenderte - URLs sehen:
- app.neosyn.ai/login -> rendert den Facebook Connect Button
- app.neosyn.ai/registration -> nach erfolgtem Login bzw. Verarbeitung des OAuth Callbacks durch das Backend, falls der Benutzeraccount noch nicht existiert
- app.neosyn.ai -> dashboard der app

Was haltet ihr davon?

Viele Grüße
Christian

**Comment by baehll** [comment]
Nur zum Verständnis: wenn du "von Python gerendert" sprichst, meinst du damit, dass ich von dir erstellte .html-Files unter diesen URLs zurückgebe? Denn es gibt auch die Möglichkeit, Templates seitens Python-Server zu rendern, also serverseitig HTML zu generieren und damit zu antworten.

**Comment by cknott** [comment]
Ich meine zweiteres, also je nach dem ob ich irgendwelche Infos von der Serverseite brauche, also bspw irgendeinen Auth Token von Meta, dann sollte dieser als HTML Attribut ausgegeben werden. Ablauf waere vermutlich so: wir definieren welche Attribute ich fuer welches HTML Template brauche und ich bereite dir das jeweilige HTML Template mit Platzhaltern vor, so dass du das Template in Python uebernehmen kannst und die Platzhalter durch echte Werte ersetzt.
Passt das so?

**Comment by baehll** [comment]
Ok, das können wir so machen.

Bezüglich der Strukturierung der Seite können wir das auch so machen, wie du vorgeschlagen hast. Wenn ich die Subdomains drinne habe, schreibe ich das hier im Issue.
