### ISSUE TITLE
Session Management

### ISSUE THREAD

**Issue by cknott** [baehll/neosyn#17]
Hi @baehll 

wie bildest du das Session Management ab, bzw. wie authentifiziere ich mich mit dem Backend oder weiss ob der derzeitige Besucher eingeloggt ist?

Viele Grüße
Christian

**Comment by baehll** [comment]
Die Registrierung und der Login laufen beide über den /auth/facebook Endpunkt. Wenn der User sich einloggt (durch die Weiterleitung über den Facebook-Login) wird ein Session Cookie gesetzt. Dieser hat aktuell eine Lifetime bis zum Session-Ende, sprich wenn der Browser geschlossen wird (oder ähnliches, je nach Browser). Wenn die Session ausgelaufen ist, wird bei Aufruf auf geschützte URLs eine Weiterleitung zum Facebook-Login durchgeführt.
Ich bin mir nicht sicher, ob im Frontend geprüft werden kann, ob der Session-Cookie bereits abgelaufen ist, dann könnte man diese unerwartete Weiterleitung verhindern. Ansonsten wäre es auch möglich, einen Endpunkt zu definieren, der widergibt, ob ein User eingeloggt ist oder nicht..

**Comment by cknott** [comment]
alternativ können wir auch einen jwt token erstellen und diesem eine eigene ttl geben und im local storage des nutzers speichern. 
generell brauchen wir aber vermutlich auf jeden fall einen endpunkt der informationen (profilbild, restl. einstellungen etc.) zum nutzer liefert. darüber kann ich dann ja auch rausfinden ob jemand eingeloggt ist oder nicht.

**Comment by baehll** [comment]
Ich würde fürs erste bei den Sessions bleiben, da ich ein Framework verwende, was den ganzen OAuth Tanz durchführt. Das verwendet nämlich die Sessions in Flask, ein Umstieg auf JWT wäre wahrscheinlich sehr aufwändig.

**Comment by baehll** [comment]
Session Cookies sind mit dem [3c0905c](https://github.com/baehll/neosyn/commit/3c0905cb2f78dc0c5caecd7fff0f1f7f207c39d8) nun für 31 Tage seit Erstellung des Cookies gültig.
