### ISSUE TITLE
Inbox spezifische Endpunkte

### ISSUE THREAD

**Issue by cknott** [baehll/neosyn#18]
Hi @baehll 

ich wuerde die Inbox folgendermassen umsetzen:
Beim Aufruf der Seite sende ich ein Request, welches die Threads fuer die Liste auf der linken Seite erhaelt.
Fuer den ersten Thread sende ich ein gesondertes Request, welches dann den Nachrichtenverlauf fuer die Darstellung in der rechten Seite enthaelt. Wuerde hierfuer ein Lazy Loading vorsehen, so dass wir nicht den kompletten Verlauf auf einmal laden muessen, sondern erst wenn der Nutzer nach oben scrollt und durch einen Klick weitere Nachrichten laden moechte. Weiss nicht wie du auf Python Seite mit Offsets umgehst, sag du einfach Bescheid welche Info du bei dem Request dann brauchst!

Kann dir nachher gerne meinen Vorschlag fuer die JSON Struktur durchschicken (falls du hierfuer noch keine hast)

Viele Grüße
Christian

**Comment by cknott** [comment]
weitere endpunkte die mir gerade auffallen:
- nachricht als gelesen markieren
- nachricht als ungelesen markieren 
- nachricht löschen

**Comment by cknott** [comment]
ich hab noch was: bei jedem thread brauche ich ja noch den bezug zum jeweiligen social media post. wuerde das auch separat anfragen, dann kann ich das idealerweise bei mehreren threads die sich auf dasselbe posting beziehen wiederverwenden und requests sparen.
es waere gut wenn ich bei jedem thread noch eine eindeutige id des social media posts zurueckbekommen wuerde, dann kann ich das in kombination mit der social media platform an einen weiteren endpunkt senden um dann die post infos (bild, beitrag, anzahl likes, anzahl kommentare, etc.) zu erhalten.

**Comment by baehll** [comment]
Wie eben in Meeting besprochen, kannst du in der Endpunkte Definition deine identifizierten Endpunkte hinschreiben und was du für Inhalte erwartest. Ich werde dann dementsprechend die API bauen, sobald ich die Seminararbeit größtenteils fertig habe.

**Comment by cknott** [comment]
hi @baehll ich habe gerade meine vorschläge für die notwendigen endpunkte in der Endpoints.md ergänzt und in dev gemerged. Magst du mal drauf schauen und wir sprechen morgen im Detail darüber?

**Comment by baehll** [comment]
Danke, dass du schon mal ein paar der Endpunkte definiert hast.
Hier ein paar Rückfragen, können wir morgen besprechen:

- in "POST /api/data/threads[/{sorting}]" ist GET auf /threads, POST auf /threads/sorting ?
- Ich habe eine Enum Tabelle für Plattformen, wie soll ich die an dich weiterleiten?
- beim Sentiment dachte ich mir, dass es ein Tupel aus (float, str) ist, float ist die "Stimmung" zwischen 0 (negativ) und 1 (positiv) und der String wäre die Kategorie (Frage, Anmerkung, Beschwerde etc.), Kategorien vielleicht auch wie die Plattformen an dich dann weiterleiten?
- auf Backend-Seite nenne ich "Threads" "Interactions", vielleicht sollten wir hier uns auf eins einigen, um die Kommunikation zu verbessern
- kannst du nochmal kennzeichnen, wo IDs vom Backend benötigt werden und wo von den Plattformen? zB bei "GET /api/data/threads/{id}", in der Struktur steht threadId und id, aber müsste nicht {id} die threadId sein?

**Comment by baehll** [comment]
Hallo @cknott ,

Hab soeben die ersten Endpunkte von S5 hinzugefügt, dabei aber ein paar Änderungen an POST/GET /api/data/threads gemacht, das steht auch in der [Doku](https://github.com/baehll/neosyn/blob/main/Endpoints.md#s5). Änderungen sind in main und dev.

In [/api/data/threads/<:threadId>](https://github.com/baehll/neosyn/blob/main/Endpoints.md#get-apidatathreadsthreadid) habe ich zudem content -> message geändert und ein weiteres Feld in den Thread Objekten hinzugefügt "interactions", die Anzahl der Interaktionen/Messages/Comments in einem Thread.

Mit Max werde ich morgen besprechen, wo und wann Daten von den Plattformen gesammelt werden sollten, da das viel Zeit auf Grund der Menge an Anfragen dauern kann, deshalb kann man Daten nur über Debug Endpunkte triggern.
Wie weit bist du mit den Endpunkten? Ich vermute, dass der Austausch Frontend/Backend nicht einfach so klappen wird.
