### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by cknott** [baehll/neosyn#5]
Hi @baehll 

ich werde heute Mittag einen deploy fähigen Stand der Coming Soon Seite haben und frage mich wie das Deployment läuft. 
In welchen Branch sollte ich meine Änderungen mergen und werden diese Änderungen dann automatisch deployed?

Viele Grüße
Christian

**Comment by baehll** [comment]
Hallo @cknott ,
Automatisch wird über den **main** Branch deployed. Merge am besten zunächst in den **dev** Branch, da der Stand im **main** Branch noch veraltet ist. Morgen früh würde ich dann das Deployment begleiten. Wenn das funktioniert, können wir im Prinzip immer deployen.

-Fabian

**Comment by cknott** [comment]
Hi @baehll 

alles klar! Noch eine Frage: ich hab über eine Environment Variable die URL für die API hinterlegt. Von Gitlab kenne ich es so, dass CI Variable definiert werden können die dann während des Builds verwendet werden. Geht das hier auch bzw. wie würdest du für die Production Umgebung die URL für die API hinterlegen?

Viele Grüße
Christian

**Comment by baehll** [comment]
Bezieht sich das auf den Build deiner Vite Applikation? Ich meine, dass ich das Thema auch schon mal hatte. So wie ich das in Erinnerung habe, werden da die ENV Variablen aus den Heroku ENV genommen, da erst dort der eigentliche Build stattfindet.

-Fabian

**Comment by cknott** [comment]
Genau, geht um den Vite Build. Kannst du die Heroku Env Vars setzen? Ich bräuchte VITE_API_URL für die Basis URL der API.

**Comment by baehll** [comment]
Ist jetzt angepasst

**Comment by cknott** [comment]
top, bist du schon am deployment? über welche url kann ich den stand dann aufrufen, neosyn.ai?

**Comment by baehll** [comment]
Deployment erfolgreich, damit schließe ich das Issue
