### ISSUE TITLE
500 bei upload von docx bei company_files endpunkt

### ISSUE THREAD

**Issue by cknott** [baehll/neosyn#61]
Dieser Stacktrace kommt nach upload von einem docx dokument.

TypeError
TypeError: The view function for 'api.company_files' did not return a valid response. The function either returned None or ended without a return statement.

Traceback (most recent call last)
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    ) -> cabc.Iterable[bytes]:
        """The WSGI server calls the Flask application object as the
        WSGI application. This calls :meth:`wsgi_app`, which can be
        wrapped to apply middleware.
        """
        return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1476, in wsgi_app
            try:
                ctx.push()
                response = self.full_dispatch_request()
            except Exception as e:
                error = e
                response = self.handle_exception(e)
            except:  # noqa: B001
                error = sys.exc_info()[1]
                raise
            return response(environ, start_response)
        finally:
File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
        # Wrap exception handlers with cross_origin
        # These error handlers will still respect the behavior of the route
        if options.get('intercept_exceptions', True):
            def _after_request_decorator(f):
                def wrapped_function(*args, **kwargs):
                    return cors_after_request(app.make_response(f(*args, **kwargs)))
                return wrapped_function
 
            if hasattr(app, 'handle_exception'):
                app.handle_exception = _after_request_decorator(
                    app.handle_exception)
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
        ctx = self.request_context(environ)
        error: BaseException | None = None
        try:
            try:
                ctx.push()
                response = self.full_dispatch_request()
            except Exception as e:
                error = e
                response = self.handle_exception(e)
            except:  # noqa: B001
                error = sys.exc_info()[1]
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 883, in full_dispatch_request
            rv = self.preprocess_request()
            if rv is None:
                rv = self.dispatch_request()
        except Exception as e:
            rv = self.handle_user_exception(e)
        return self.finalize_request(rv)
 
    def finalize_request(
        self,
        rv: ft.ResponseReturnValue | HTTPException,
        from_error_handler: bool = False,
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 902, in finalize_request
        with the `from_error_handler` flag.  If enabled, failures in
        response processing will be logged and otherwise ignored.
 
        :internal:
        """
        response = self.make_response(rv)
        try:
            response = self.process_response(response)
            request_finished.send(
                self, _async_wrapper=self.ensure_sync, response=response
            )
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1174, in make_response
                    " (body, status), or (body, headers)."
                )
 
        # the body must not be None
        if rv is None:
            raise TypeError(
                f"The view function for {request.endpoint!r} did not"
                " return a valid response. The function either returned"
                " None or ended without a return statement."
            )
 
TypeError: The view function for 'api.company_files' did not return a valid response. The function either returned None or ended without a return statement.
This is the Copy/Paste friendly version of the traceback.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 883, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 902, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1174, in make_response
    raise TypeError(
TypeError: The view function for 'api.company_files' did not return a valid response. The function either returned None or ended without a return statement.

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error. If you enable JavaScript you can also use additional features such as code execution (if the evalex feature is enabled), automatic pasting of the exceptions and much more.
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.
Console Locked
The console is locked and needs to be unlocked by entering the PIN. You can find the PIN printed out on the standard output of your shell that runs the server.

PIN:

**Comment by cknott** [comment]
passiert auch bei upload von einem pdf

**Comment by baehll** [comment]
Den Fehler selber konnte ich zweimal provozieren:
- wenn man nicht den ganzen Registrierungsprozess am Stück durchläuft, existiert evtl. der Orga Ordner im Uploads Ordner nicht (folder_path in der DB) und dann kann da auch nichts gespeichert werden
- wenn man die DB gelockt hat, weil man über andere Wege Daten geändert und noch nicht gespeichert hat

Für den ersten Fall push ich gleich was auf dev
Schau am besten auch immer, was in der Konsole des Servers steht, bis ich logging implementiert habe

**Comment by cknott** [comment]
ich laufe eigentlich immer den gesamten prozess durch, deshalb kanns an punkt 1 eigentlich nicht liegen.
in der konsole des servers steht komischerweise auch nichts, immer nur im response vom request.
was mich auch wundert ist, dass im stacktrace nirgends eine datei aus dem projekt angegeben ist, das bezieht sich ja alles auf flask.

ich habe gerade noch kurz in den python code geschaut und gesehen, dass im falle einer exception nichts returned sondern nur geprinted wird und das gefällt flask wohl nicht. wenn ich die exception returne, kommt folgendes:

{
    "error": "Traceback (most recent call last):\n  File \"/app/server/web/api/api.py\", line 134, in company_files\n    assistant_utils.init_assistant(config(\"COMPANY_FILE_UPLOAD_FOLDER\"), successful, orga)\n  File \"/app/server/utils/assistant_utils.py\", line 27, in init_assistant\n    vec_storage = init_vector_storage(orga.folder_path + \"_VECTOR_STORE\", file_ids)\n  File \"/app/server/utils/assistant_utils.py\", line 16, in init_vector_storage\n    return GPTConfig().CLIENT.beta.vector_stores.create(\nAttributeError: 'Beta' object has no attribute 'vector_stores'\n"
}

kannst du damit was anfangen?

**Comment by baehll** [comment]
Ok das scheint dann vielleicht an deinen Python Modulen liegen, versuch die einmal zu updaten

`GPTConfig().CLIENT.beta.vector_stores.create(\nAttributeError: 'Beta' object has no attribute 'vector_stores'\n"`
Den Fehler bekomme ich bei einer neu aufgesetzten Umgebung nicht, und der Aufruf selbst passt zur Doku

**Comment by baehll** [comment]
Hast aber recht, da fehlte ein return im except Block!
