### ISSUE TITLE
CORS bei URLs mit Authentifizierung

### ISSUE THREAD

**Issue by baehll** [baehll/neosyn#74]
Hallo @cknott 

beim hochladen des Profilbilds kriege ich einen CORS Fehler:

POST https://quiet-mountain-69143-51eb8184b186.herokuapp.com/api/init_user

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://quiet-mountain-69143-51eb8184b186.herokuapp.com/api/init_user. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt). Statuscode: 503.

[Hier](https://github.com/corydolphin/flask-cors/issues/289#issuecomment-1075103344) wurde erwähnt, dass auch bei den Requests dieses `withCredentials` Feld mitgeschickt werden muss, kannst du schauen, ob du das macht?

Das Problem taucht erst bei den authentifizierten Routen `/api/*`, da die `/auth/*` keine Authentifizierung benötigen

**Comment by cknott** [comment]
hi @baehll habe gerade die änderung gepusht. ists safe in main zu mergen?

**Comment by baehll** [comment]
Hab ich grade gemacht
leider kann man das lokal nicht testen, weil CORS da anscheinend nicht relevant ist?

**Comment by baehll** [comment]
Mir ist auch noch das in der Konsole aufgefallen, nachdem man mit dem Key zum login weitergeleitet wird

Das Cookie "session" wurde abgelehnt, weil es sich in einem seitenübergreifenden Kontext befindet und sein "SameSite" auf "Lax" oder "Strict" gesetzt ist.

@cknott weißt du, was das bedeutet?

**Comment by baehll** [comment]
Ok das Problem war, dass man die Seite unter unaite.ai öffnet, aber für die VITE_API_URL die heroku-url verwendet wurde. Dadurch entstand der CORS Fehler und der Fehler mit dem Cookie

Uploads sollten nun klappen.
