### ISSUE TITLE
Early Access Umleitung

### ISSUE THREAD

**Issue by baehll** [baehll/neosyn#84]
Hey @cknott 

Aktuell wird ja nach einer Response von POST /auth/early_access im Frontend auf /login.html weitergeleitet
Ich würde vorschlagen, dass stattdessen bei einem POST /auth/early_access Call der Server selbst weiterleitet und somit die /login.html nicht einfach zugänglich ist.
Wie sollte man da bei einem Fehlversuch reagieren? Könnte ich einfach bei Erfolg auf /login.html weiterleiten und bei einem Fehlschlag HTTP 500 + Error ?

**Comment by cknott** [comment]
hi @baehll ich befürchte dass eine serverseitige weiterleitung bei einem xhr request ins leere läuft, bzw nicht beim client als weiterleitung ankommt. ich könnte aber nach der prüfung des passworts ein weiteres post request über ein verstecktes formular absenden (an einen von dir zu definierenden endpunkt) der ebenfalls das eingegebene passwort enthält und dass du dann entsprechend weiterleiten kannst.

**Comment by baehll** [comment]
Ok das würde ich so machen, falls beim zweiten senden des Keys ein Problem auftritt, wird keine Weiterleitung stattfinden

**Comment by baehll** [comment]
Implementiert in dev
