### ISSUE TITLE
Sortierung von Messages fuer einen Thread

### ISSUE THREAD

**Issue by cknott** [baehll/neosyn#88]
hi @baehll 
bei dem endpunkt der mir messages für eine threadid liefert stimmt aus meiner sicht die sortierung im response nicht. die ids sind zwar aufsteigend, aber das datum der messages scheint durchmischt zu sein, kannst du das prüfen?

**Comment by baehll** [comment]
Jo hast recht, das ist die normale Sortierung aus der DB nach ID

**Comment by baehll** [comment]
gefixed in dev
