### ISSUE TITLE
Senden von Nachrichten / Logging

### ISSUE THREAD

**Issue by cknott** [baehll/neosyn#89]
hi @baehll 
ich kriege beim versenden von nachrichten diesen fehler:

{
    "error": "Traceback (most recent call last):\n  File \"/app/server/web/api/data/threads.py\", line 188, in post_message\n    IGApiFetcher.getComments(oauth.token['access_token'], thread.media)\n  File \"/app/server/utils/IGApiFetcher.py\", line 300, in getComments\n    res = _getInstagramData(access_token, f\"/{media.fb_id}/comments\")\n  File \"/app/server/utils/IGApiFetcher.py\", line 30, in _getInstagramData\n    if \"data\" in ids.json():\nAttributeError: 'NoneType' object has no attribute 'json'\n"
}

ist es möglich dass solche fehler direkt in der konsole ausgegeben werden? ich musste mir den stacktrace in das json response reinpacken um die exception zu sehen.

**Comment by baehll** [comment]
ich starte meinen Flask server nicht in docker und sehe sie dort in der konsole, vielleicht im Container?

**Comment by baehll** [comment]
Hi @cknott kannst du mir die IDs zu der Request geben? 

Den Fehler hatte ich bis jetzt noch nicht gesehen, könnte evtl. daran liegen, dass ich dich ja über meinen Account posten lasse (wenn du meine db instanz benutzt). Anscheinend ist die Antwort von facebook hier anders als normalerweise

**Comment by cknott** [comment]
@baehll ok, ich habe meinen stand in dev gemerged, kannst du bei dir mal prüfen ob das funktioniert?

**Comment by baehll** [comment]
Ok ich habe auch eine Fehlermeldung von FB beim Posten eines Kommentars, aber komischerweise wird es dennoch gepostet ..
