### ISSUE TITLE
Exception bei Post Endpunkt

### ISSUE THREAD

**Issue by cknott** [baehll/neosyn#91]
hi @baehll 
beim abrufen des posts zu einem thread kriege ich folgende exception:

{
    "error": "Traceback (most recent call last):\n  File \"/app/server/web/api/api.py\", line 153, in get_post_information\n    return jsonify(current_user), 200\n  File \"/usr/local/lib/python3.8/site-packages/flask/json/__init__.py\", line 170, in jsonify\n    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]\n  File \"/usr/local/lib/python3.8/site-packages/flask/json/provider.py\", line 214, in response\n    f\"{self.dumps(obj, **dump_args)}\\n\", mimetype=self.mimetype\n  File \"/usr/local/lib/python3.8/site-packages/flask/json/provider.py\", line 179, in dumps\n    return json.dumps(obj, **kwargs)\n  File \"/usr/local/lib/python3.8/json/__init__.py\", line 234, in dumps\n    return cls(\n  File \"/usr/local/lib/python3.8/json/encoder.py\", line 201, in encode\n    chunks = list(chunks)\n  File \"/usr/local/lib/python3.8/json/encoder.py\", line 438, in _iterencode\n    o = _default(o)\n  File \"/usr/local/lib/python3.8/site-packages/flask/json/provider.py\", line 121, in _default\n    raise TypeError(f\"Object of type {type(o).__name__} is not JSON serializable\")\nTypeError: Object of type LocalProxy is not JSON serializable\n"
}

**Comment by baehll** [comment]
```get_post_information\n return jsonify(current_user), 200``` <- das ist ein veralteter Stand, das ist schon in dev gefixt
