### ISSUE TITLE
bookmark status an einem thread zurückgeben

### ISSUE THREAD

**Issue by cknott** [baehll/neosyn#95]
hi @baehll 
es wäre geschickt, wenn ich über den /api/data/threads endpunkt ebenfalls den bookmarked status erhalten könnte.
dann muss ich bei der thread detail ansicht nicht noch ein (oder mehrere) weitere requests senden um rauszufinden ob dieser thread bookmarked ist.

**Comment by baehll** [comment]
implementiert
