### ISSUE TITLE
/api/company_files leerer Aufruf bei keinen Dateien

### ISSUE THREAD

**Issue by baehll** [baehll/neosyn#99]
hallo @cknott 

wenn in der UI das hochladen von Dateien übersprungen wird, sollte auch ein Post gegen /api/company_files ohne body stattfinden, damit die OpenAI Instanzen erstellt werden

**Comment by baehll** [comment]
hallo @cknott 

das selbe sollte auch bei der Eingabe von Username, Company Name und überspringen vom Logo file statt finden, da ansonsten nicht die nötigen DB Objekte erstellt werden bzw initialisiert werden können

**Comment by cknott** [comment]
hi @baehll alles klar, ist jetzt in dev!

**Comment by baehll** [comment]
Anscheinend entsteht beim überspringen vom Upload von company_files eine Dauerschleife, es werden sehr viele Aufrufe auf /api/company_files gemacht, kannst du das checken?

**Comment by cknott** [comment]
ist gefixt in dev!

**Comment by baehll** [comment]
hi @cknott 
Beim Klicken auf "Continue" bzw. "Later" mit bzw. ohne Dateien findet nicht die Weiterleitung zur app statt

kannst du dir das angucken?

**Comment by cknott** [comment]
@baehll ist gefixt in dev!
